# Generated by Django 4.1.5 on 2023-01-27 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nome do Produto"
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Descrição"
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Preço")),
                (
                    "images",
                    models.ImageField(
                        upload_to="photos/products", verbose_name="Imagem"
                    ),
                ),
                ("stock", models.IntegerField(verbose_name="Estoque")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Disponível"),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "modifield_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data modificação"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.category",
                    ),
                ),
            ],
        ),
    ]
