# Generated by Django 4.1.5 on 2023-02-27 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_product_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Variation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variations_category",
                    models.CharField(
                        choices=[("color", "color"), ("size", "size")],
                        max_length=100,
                        verbose_name="Variação de categoria",
                    ),
                ),
                (
                    "variation_value",
                    models.CharField(max_length=100, verbose_name="Nome variável"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "created_date",
                    models.DateTimeField(auto_now=True, verbose_name="Data criação"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
            ],
        ),
    ]
